import {
  DAY,
  type CrmState,
  type Stage,
} from "./types";

/**
 * Realistic agency-flavored demo data. All timestamps are relative to `now`
 * so Pulse always has a healthy mix of fresh, cooling and at-risk deals no
 * matter when the demo is opened.
 */

export const AGENCY_STAGES: Stage[] = [
  { id: "new", name: "New", kind: "open" },
  { id: "contacted", name: "Contacted", kind: "open" },
  { id: "qualified", name: "Qualified", kind: "open" },
  { id: "proposal", name: "Proposal sent", kind: "open" },
  { id: "negotiation", name: "Negotiation", kind: "open" },
  { id: "won", name: "Won", kind: "won" },
  { id: "lost", name: "Lost", kind: "lost" },
];

export const SIMPLE_STAGES: Stage[] = [
  { id: "lead", name: "Lead", kind: "open" },
  { id: "talks", name: "In talks", kind: "open" },
  { id: "won", name: "Won", kind: "won" },
  { id: "lost", name: "Lost", kind: "lost" },
];

export function makeSeedState(now: number = Date.now()): CrmState {
  const d = (days: number) => now - days * DAY;
  /** `days` from today at `hour`:00 local time. */
  const at = (days: number, hour: number) => {
    const t = new Date(now + days * DAY);
    t.setHours(hour, 0, 0, 0);
    return t.getTime();
  };

  return {
    workspace: { name: "Franko Labs", plan: "studio" },
    stages: AGENCY_STAGES,
    onboarded: false,
    readNotifIds: [],
    ui: { openRequest: null },

    companies: [
      {
        id: "co-voyagr",
        name: "Voyagr",
        domain: "voyagr.app",
        industry: "Travel tech",
        location: "Austin, TX",
        isClient: true,
        notes: "Flagship client. Full platform build — site, booking flow, brand.",
      },
      {
        id: "co-northbeam",
        name: "Northbeam Dental",
        domain: "northbeamdental.com",
        industry: "Healthcare",
        location: "Portland, OR",
        isClient: true,
        notes: "Three-location practice. Site redesign live; SEO retainer ongoing.",
      },
      {
        id: "co-kettle",
        name: "Kettle & Co.",
        domain: "kettleandco.shop",
        industry: "Specialty coffee",
        location: "Chicago, IL",
        isClient: false,
        notes: "Roastery expanding into subscriptions. Came via Instagram.",
      },
      {
        id: "co-atlas",
        name: "Atlas Fitness",
        domain: "atlasfit.io",
        industry: "Fitness",
        location: "Denver, CO",
        isClient: false,
        notes: "Two gyms, launching a coaching app. Needs booking + CRM.",
      },
      {
        id: "co-meridian",
        name: "Meridian Legal",
        domain: "meridianlegal.com",
        industry: "Legal services",
        location: "Seattle, WA",
        isClient: false,
        notes: "Boutique firm. Referral from Northbeam. Slow-moving but serious.",
      },
      {
        id: "co-harborview",
        name: "Harborview Realty",
        domain: "harborviewrealty.com",
        industry: "Real estate",
        location: "San Diego, CA",
        isClient: false,
        notes: "Wants IDX listings + lead capture. Budget confirmed.",
      },
      {
        id: "co-greenleaf",
        name: "GreenLeaf Landscaping",
        domain: "greenleaf.pro",
        industry: "Home services",
        location: "Nashville, TN",
        isClient: false,
        notes: "Found us through the website audit offer.",
      },
      {
        id: "co-pixelthread",
        name: "Pixel & Thread",
        domain: "pixelthread.studio",
        industry: "E-commerce apparel",
        location: "Brooklyn, NY",
        isClient: false,
        notes: "Shopify migration inquiry. Ghosted after first call last quarter.",
      },
    ],

    contacts: [
      {
        id: "ct-maya",
        name: "Maya Chen",
        email: "maya@voyagr.app",
        phone: "(512) 555-0142",
        role: "Co-founder & CEO",
        companyId: "co-voyagr",
        hue: 160,
        tags: ["client", "decision-maker"],
        createdAt: d(94),
        notes: "Prefers Loom updates over calls. Big on weekly momentum.",
      },
      {
        id: "ct-daniel",
        name: "Daniel Osei",
        email: "daniel@voyagr.app",
        phone: "(512) 555-0177",
        role: "Head of Product",
        companyId: "co-voyagr",
        hue: 210,
        tags: ["client"],
        createdAt: d(80),
        notes: "Owns the booking-flow roadmap. Reviews everything in Figma.",
      },
      {
        id: "ct-sarah",
        name: "Dr. Sarah Whitfield",
        email: "sarah@northbeamdental.com",
        phone: "(503) 555-0119",
        role: "Owner",
        companyId: "co-northbeam",
        hue: 280,
        tags: ["client", "decision-maker"],
        createdAt: d(150),
        notes: "Cares about new-patient bookings above all. Monthly report call.",
      },
      {
        id: "ct-tom",
        name: "Tom Reyes",
        email: "tom@kettleandco.shop",
        phone: "(312) 555-0163",
        role: "Founder",
        companyId: "co-kettle",
        hue: 30,
        tags: ["lead", "e-commerce"],
        createdAt: d(12),
        notes: "Wants subscriptions live before holiday season.",
      },
      {
        id: "ct-jess",
        name: "Jess Kowalski",
        email: "jess@atlasfit.io",
        phone: "(720) 555-0184",
        role: "Co-owner",
        companyId: "co-atlas",
        hue: 0,
        tags: ["lead", "decision-maker"],
        createdAt: d(21),
        notes: "Compared us against two other agencies. Liked the OS pitch.",
      },
      {
        id: "ct-victor",
        name: "Victor Nguyen",
        email: "vnguyen@meridianlegal.com",
        phone: "(206) 555-0155",
        role: "Managing Partner",
        companyId: "co-meridian",
        hue: 240,
        tags: ["lead", "referral"],
        createdAt: d(38),
        notes: "Needs partner buy-in. Decision cycle measured in months, not weeks.",
      },
      {
        id: "ct-alina",
        name: "Alina Petrova",
        email: "alina@harborviewrealty.com",
        phone: "(619) 555-0102",
        role: "Broker / Owner",
        companyId: "co-harborview",
        hue: 330,
        tags: ["lead", "decision-maker"],
        createdAt: d(16),
        notes: "Very responsive. Wants to launch before spring listings.",
      },
      {
        id: "ct-marcus",
        name: "Marcus Hill",
        email: "marcus@greenleaf.pro",
        phone: "(615) 555-0136",
        role: "Owner",
        companyId: "co-greenleaf",
        hue: 110,
        tags: ["lead", "audit"],
        createdAt: d(2),
        notes: "Requested the free website audit. Current site is a 2014 template.",
      },
      {
        id: "ct-priya",
        name: "Priya Raman",
        email: "priya@pixelthread.studio",
        phone: "(718) 555-0191",
        role: "Creative Director",
        companyId: "co-pixelthread",
        hue: 60,
        tags: ["lead", "cold"],
        createdAt: d(70),
        notes: "Went quiet after pricing conversation. Worth one more touch.",
      },
      {
        id: "ct-ben",
        name: "Ben Carter",
        email: "ben.carter@gmail.com",
        phone: "(415) 555-0129",
        role: "Indie founder",
        companyId: null,
        hue: 190,
        tags: ["lead", "waitlist"],
        createdAt: d(5),
        notes: "Joined the Franko OS waitlist; asked about white-label options.",
      },
    ],

    deals: [
      {
        id: "dl-voyagr-2",
        name: "Voyagr — booking flow phase 2",
        companyId: "co-voyagr",
        contactId: "ct-maya",
        stageId: "negotiation",
        value: 24_000,
        source: "Existing client",
        createdAt: d(18),
        stageChangedAt: d(3),
        closedAt: null,
      },
      {
        id: "dl-kettle",
        name: "Kettle & Co. — subscription storefront",
        companyId: "co-kettle",
        contactId: "ct-tom",
        stageId: "proposal",
        value: 14_500,
        source: "Instagram",
        createdAt: d(12),
        stageChangedAt: d(9),
        closedAt: null,
      },
      {
        id: "dl-atlas",
        name: "Atlas Fitness — site + booking system",
        companyId: "co-atlas",
        contactId: "ct-jess",
        stageId: "proposal",
        value: 18_000,
        source: "Referral",
        createdAt: d(21),
        stageChangedAt: d(6),
        closedAt: null,
      },
      {
        id: "dl-harborview",
        name: "Harborview Realty — listings platform",
        companyId: "co-harborview",
        contactId: "ct-alina",
        stageId: "qualified",
        value: 22_000,
        source: "Google search",
        createdAt: d(16),
        stageChangedAt: d(2),
        closedAt: null,
      },
      {
        id: "dl-meridian",
        name: "Meridian Legal — firm site + intake automation",
        companyId: "co-meridian",
        contactId: "ct-victor",
        stageId: "qualified",
        value: 16_500,
        source: "Referral",
        createdAt: d(38),
        stageChangedAt: d(14),
        closedAt: null,
      },
      {
        id: "dl-greenleaf",
        name: "GreenLeaf — website rebuild",
        companyId: "co-greenleaf",
        contactId: "ct-marcus",
        stageId: "new",
        value: 6_500,
        source: "Website audit",
        createdAt: d(2),
        stageChangedAt: d(2),
        closedAt: null,
      },
      {
        id: "dl-ben",
        name: "Ben Carter — white-label Franko OS",
        companyId: null,
        contactId: "ct-ben",
        stageId: "contacted",
        value: 9_000,
        source: "Waitlist",
        createdAt: d(5),
        stageChangedAt: d(4),
        closedAt: null,
      },
      {
        id: "dl-pixelthread",
        name: "Pixel & Thread — Shopify migration",
        companyId: "co-pixelthread",
        contactId: "ct-priya",
        stageId: "contacted",
        value: 11_000,
        source: "Contact form",
        createdAt: d(70),
        stageChangedAt: d(31),
        closedAt: null,
      },
      {
        id: "dl-voyagr-1",
        name: "Voyagr — platform build phase 1",
        companyId: "co-voyagr",
        contactId: "ct-maya",
        stageId: "won",
        value: 32_000,
        source: "Referral",
        createdAt: d(94),
        stageChangedAt: d(61),
        closedAt: d(61),
      },
      {
        id: "dl-northbeam",
        name: "Northbeam Dental — redesign + SEO retainer",
        companyId: "co-northbeam",
        contactId: "ct-sarah",
        stageId: "won",
        value: 21_000,
        source: "Google search",
        createdAt: d(150),
        stageChangedAt: d(118),
        closedAt: d(118),
      },
      {
        id: "dl-lakeside",
        name: "Lakeside Auto — dealer site",
        companyId: null,
        contactId: null,
        stageId: "lost",
        value: 8_000,
        source: "Cold outreach",
        createdAt: d(55),
        stageChangedAt: d(40),
        closedAt: d(40),
      },
    ],

    tasks: [
      {
        id: "tk-1",
        title: "Send revised proposal to Kettle & Co. with subscription tiers",
        dueAt: d(2),
        done: false,
        dealId: "dl-kettle",
        contactId: "ct-tom",
        createdAt: d(9),
      },
      {
        id: "tk-2",
        title: "Follow up with Victor on partner review",
        dueAt: d(4),
        done: false,
        dealId: "dl-meridian",
        contactId: "ct-victor",
        createdAt: d(14),
      },
      {
        id: "tk-3",
        title: "Prepare contract draft for Voyagr phase 2",
        dueAt: now + DAY,
        done: false,
        dealId: "dl-voyagr-2",
        contactId: "ct-maya",
        createdAt: d(3),
      },
      {
        id: "tk-4",
        title: "Run website audit for GreenLeaf and send summary",
        dueAt: now,
        done: false,
        dealId: "dl-greenleaf",
        contactId: "ct-marcus",
        createdAt: d(2),
      },
      {
        id: "tk-5",
        title: "Book demo call with Alina — listings platform walkthrough",
        dueAt: now + 2 * DAY,
        done: false,
        dealId: "dl-harborview",
        contactId: "ct-alina",
        createdAt: d(2),
      },
      {
        id: "tk-6",
        title: "Send Northbeam monthly SEO report",
        dueAt: now + 5 * DAY,
        done: false,
        dealId: null,
        contactId: "ct-sarah",
        createdAt: d(6),
      },
      {
        id: "tk-7",
        title: "Re-engage Priya — one-touch check-in email",
        dueAt: d(20),
        done: false,
        dealId: "dl-pixelthread",
        contactId: "ct-priya",
        createdAt: d(31),
      },
      {
        id: "tk-8",
        title: "Qualify Ben's white-label use case",
        dueAt: d(1),
        done: true,
        dealId: "dl-ben",
        contactId: "ct-ben",
        createdAt: d(5),
      },
    ],

    activities: [
      {
        id: "ac-1",
        type: "meeting",
        summary: "Scope call with Maya & Daniel — phase 2 covers payments, itineraries and the mobile booking flow.",
        at: d(3),
        dealId: "dl-voyagr-2",
        contactId: "ct-maya",
        companyId: "co-voyagr",
        clientVisible: true,
      },
      {
        id: "ac-2",
        type: "stage",
        summary: "Moved to Negotiation — budget approved, final scope under review.",
        at: d(3),
        dealId: "dl-voyagr-2",
        contactId: "ct-maya",
        companyId: "co-voyagr",
        clientVisible: true,
      },
      {
        id: "ac-3",
        type: "email",
        summary: "Sent proposal — storefront rebuild + subscription engine, two pricing options.",
        at: d(9),
        dealId: "dl-kettle",
        contactId: "ct-tom",
        companyId: "co-kettle",
        clientVisible: false,
      },
      {
        id: "ac-4",
        type: "call",
        summary: "Jess asked for a phased payment schedule; sending updated proposal.",
        at: d(6),
        dealId: "dl-atlas",
        contactId: "ct-jess",
        companyId: "co-atlas",
        clientVisible: false,
      },
      {
        id: "ac-5",
        type: "meeting",
        summary: "Discovery call — needs IDX feed, neighborhood pages, lead routing to 3 agents.",
        at: d(2),
        dealId: "dl-harborview",
        contactId: "ct-alina",
        companyId: "co-harborview",
        clientVisible: false,
      },
      {
        id: "ac-6",
        type: "email",
        summary: "Victor confirmed interest; waiting on partner meeting for budget sign-off.",
        at: d(14),
        dealId: "dl-meridian",
        contactId: "ct-victor",
        companyId: "co-meridian",
        clientVisible: false,
      },
      {
        id: "ac-7",
        type: "system",
        summary: "Lead captured from website audit form.",
        at: d(2),
        dealId: "dl-greenleaf",
        contactId: "ct-marcus",
        companyId: "co-greenleaf",
        clientVisible: false,
      },
      {
        id: "ac-8",
        type: "call",
        summary: "Intro call with Ben — wants Franko OS under his own brand for 5 clients.",
        at: d(4),
        dealId: "dl-ben",
        contactId: "ct-ben",
        companyId: null,
        clientVisible: false,
      },
      {
        id: "ac-9",
        type: "email",
        summary: "Pricing conversation — Priya said she'd 'circle back after the season'.",
        at: d(31),
        dealId: "dl-pixelthread",
        contactId: "ct-priya",
        companyId: "co-pixelthread",
        clientVisible: false,
      },
      {
        id: "ac-10",
        type: "note",
        summary: "Phase 1 retrospective: launch hit 99.98% uptime, booking conversion up 34%.",
        at: d(58),
        dealId: "dl-voyagr-1",
        contactId: "ct-maya",
        companyId: "co-voyagr",
        clientVisible: true,
      },
      {
        id: "ac-11",
        type: "system",
        summary: "Deal won — Northbeam Dental redesign + SEO retainer signed.",
        at: d(118),
        dealId: "dl-northbeam",
        contactId: "ct-sarah",
        companyId: "co-northbeam",
        clientVisible: true,
      },
      {
        id: "ac-12",
        type: "email",
        summary: "Sent March SEO report — organic new-patient bookings up 22% month over month.",
        at: d(8),
        dealId: null,
        contactId: "ct-sarah",
        companyId: "co-northbeam",
        clientVisible: true,
      },
      {
        id: "ac-13",
        type: "note",
        summary: "Voyagr phase 2 kickoff scheduled — design sprint starts next week.",
        at: d(1),
        dealId: "dl-voyagr-2",
        contactId: "ct-daniel",
        companyId: "co-voyagr",
        clientVisible: true,
      },
    ],

    events: [
      {
        id: "ev-1",
        title: "Demo call — listings platform walkthrough",
        kind: "call",
        startAt: at(0, 10),
        durationMin: 45,
        dealId: "dl-harborview",
        contactId: "ct-alina",
        notes: "Show the IDX prototype and lead-routing flow.",
        done: false,
      },
      {
        id: "ev-2",
        title: "Send revised Kettle & Co. proposal",
        kind: "deadline",
        startAt: at(0, 15),
        durationMin: 30,
        dealId: "dl-kettle",
        contactId: "ct-tom",
        notes: "",
        done: false,
      },
      {
        id: "ev-3",
        title: "Voyagr phase 2 — design sprint kickoff",
        kind: "meeting",
        startAt: at(1, 11),
        durationMin: 90,
        dealId: "dl-voyagr-2",
        contactId: "ct-daniel",
        notes: "Figma walkthrough with Daniel's team.",
        done: false,
      },
      {
        id: "ev-4",
        title: "Qualification call — white-label scope",
        kind: "call",
        startAt: at(2, 14),
        durationMin: 30,
        dealId: "dl-ben",
        contactId: "ct-ben",
        notes: "",
        done: false,
      },
      {
        id: "ev-5",
        title: "Scope review with Maya",
        kind: "meeting",
        startAt: at(-1, 14),
        durationMin: 60,
        dealId: "dl-voyagr-2",
        contactId: "ct-maya",
        notes: "Recap in the phase-2 doc.",
        done: true,
      },
      {
        id: "ev-6",
        title: "Northbeam monthly SEO report due",
        kind: "deadline",
        startAt: at(4, 12),
        durationMin: 30,
        dealId: null,
        contactId: "ct-sarah",
        notes: "",
        done: false,
      },
      {
        id: "ev-7",
        title: "Meridian partner-meeting follow-up",
        kind: "call",
        startAt: at(3, 9),
        durationMin: 30,
        dealId: "dl-meridian",
        contactId: "ct-victor",
        notes: "Victor said partners meet mid-week.",
        done: false,
      },
    ],

    rules: [
      {
        id: "rule-1",
        name: "Follow up after proposal",
        enabled: true,
        trigger: { type: "stage-enter", stageId: "proposal" },
        action: {
          type: "create-task",
          title: "Follow up on proposal — {deal}",
          offsetDays: 3,
        },
      },
      {
        id: "rule-2",
        name: "Announce wins in the client portal",
        enabled: true,
        trigger: { type: "deal-won" },
        action: {
          type: "portal-update",
          text: "Project kicked off: {deal}. Welcome aboard — your portal is live.",
        },
      },
    ],

    team: [
      {
        id: "tm-1",
        name: "Bohdan Lysenko",
        email: "hello@frankolabs.com",
        role: "Owner",
        hue: 160,
      },
      {
        id: "tm-2",
        name: "Ava Martinez",
        email: "ava@frankolabs.com",
        role: "Member",
        hue: 300,
      },
    ],
  };
}
